# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request_target:
    branches: [ "main" ]
    
jobs:
  run-ci-pipeline:
    uses: daniel-test-bed/Pipeline-security-tests/.github/workflows/base.yml@main
    secrets: inherit
    with: 
      myvalue: "I was passed in!"
      myOtherVale: "so was I..."
